Vagrant.configure("2") do |config|
 config.vm.box = "ubuntu/xenial64"
  config.vm.provision :shell, path: "vagrant_scripts/install-rvm.sh", args: "stable", privileged: false
  config.vm.provision :shell, path: "vagrant_scripts/install-ruby.sh", args: "2.5", privileged: false

  config.vm.provision :shell, path: "vagrant_scripts/bundle.sh", privileged: false
end
